name: production deployment
on:
  push:
    branches:
      - master
env:
  GCP_PROJECT: soroha
  GCS_DEST: gs://app.soroha.work/
  CACHE_CONTROL: no-store
jobs:
  build:
    name: production deployment
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: yarn install
        run: yarn install
      - name: check
        run: yarn check
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '285.0.0'
          project_id: ${{ env.GCP_PROJECT_ID }}
          service_account_email: ${{ secrets.GCS_SA_EMAIL_PROD }}
          service_account_key: ${{ secrets.GCP_SA_SECRET_PROD }}
          export_default_credentials: true
      - name: Build
        run: yarn build
      - name: Deploy
        run: gsutil -m -h "Cache-Control:${{ env.CACHE_CONTROL }}" rsync -dr build/ ${{ env.GCS_DEST }}
